name: Changelog generator

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Configure Git
        if: github.event.pull_request.merged == true
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
          git checkout ${{ github.head_ref }}
      - name: Get date
        if: github.event.pull_request.merged == true
        run: |
          DATE=$(date -u +'%d-%m-%Y %a')
      - name: Write changelog
        if: github.event.pull_request.merged == true
        env:
          PR_NUMBER: "${{ github.event.pull_request.number }}"
          PR_TITLE: "${{ github.event.pull_request.title }}"
          PR_AUTHOR: "${{ github.triggering_actor }}"
          PR_REVIEWER: "${{ github.event.pull_request.requested_reviewers }}"
        run: |
          touch "${{ inputs.path }}/log.csv"
          OLD_CONTENT=$(cat "${{ inputs.path }}/log.csv")
          NEW_CONTENT="$PR_NUMBER,$PR_TITLE,$PR_AUTHOR,$PR_REVIEWER,$DATE\n$OLD_CONTENT"
          echo -e "$NEW_CONTENT" > "${{ inputs.path }}/log.csv"
      - name: Commit and push changelog
        if: github.event.pull_request.merged == true
        run: |
          git add "${{ inputs.path }}/log.csv"
          git commit -m "Update changelog"
          git push origin ${{ github.head_ref }}
