name: Changelog generator

on:
  workflow_call:
    inputs:
      path:
        required: true
        type: string

jobs:
  log:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Configure Git
        if: github.event.pull_request.merged == false
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
      - name: Fetch PR information
        if: github.event.pull_request.merged == false
        run: |
          COMMIT_ID=$(echo ${{github.event.pull_request.head.sha}} | cut -c1-7)
          DATA=$(date -u +'%d-%m-%Y %a')
          git checkout ${{ github.head_ref }}
      - name: Write changelog
        if: github.event.pull_request.merged == false
        env:
          PR_NUMBER: "${{github.event.pull_request.number}}"
          COMMIT_TITLE: "${{github.event.pull_request.title}}"
          AUTHOR: "${{ github.actor }}"
        run: |
          touch "${{ inputs.path }}/log.csv"
          OLD_CONTENT=$(cat "${{ inputs.path }}/log.csv")
          NEW_CONTENT="$COMMIT_ID,$PR_NUMBER,$COMMIT_TITLE,$AUTHOR,$DATA\n$OLD_CONTENT"
          echo -e "$NEW_CONTENT" > "${{ inputs.path }}/log.csv"
      - name: Commit and push changelog
        if: github.event.pull_request.merged == false
        run: |
          git add "${{ inputs.path }}/log.csv"
          git commit -m "Update changelog"
          git push origin ${{ github.head_ref }}