name: Changed file info fetcher

on:
  workflow_call:
    outputs:
      file_path:
        description: "The path to the changed file's directory"
        value: ${{ jobs.fetch.outputs.file_path }}
      file_name:
        description: "The name of the changed file"
        value: ${{ jobs.fetch.outputs.file_name }}
      latest_version:
        description: "The current document version"
        value: ${{ jobs.fetch.outputs.latest_version }}

jobs:
  fetch:
    name: Fetch changed file info
    runs-on: ubuntu-latest
    outputs:
      file_path: '${{ steps.path.outputs.file_path }}'
      file_name: '${{ steps.name.outputs.file_name }}'
      latest_version: '${{ steps.version.outputs.latest_version }}'

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Get changed file
        id: files
        uses: tj-actions/changed-files@v40
        with:
          files: |
            **.typ
            Glossario.json
          files_ignore: template.typ
      - name: Extract path
        id: path
        run: |
          FILES="${{ steps.files.outputs.all_changed_files }}"
          echo "FILE_PATH=$(dirname "$FILES")" >> $GITHUB_OUTPUT
      - name: Extract name w/o extension
        id: name
        run: |
          FILES="${{ steps.files.outputs.all_changed_files }}"
          echo "FILE_NAME=$(basename "${FILES}" .typ)" >> $GITHUB_OUTPUT
      - name: Get latest version
        id: version
        run: |
          echo "LATEST_VERSION=$(head -n1 "${{ steps.path.outputs.file_path }}/log.csv" | cut -d',' -f1)" >> $GITHUB_OUTPUT
      - name: Output to summary
        run: |
          echo "::notice::Path: ${{ steps.path.outputs.file_path }}"
          echo "::notice::Name: ${{ steps.name.outputs.file_name }}"
          echo "::notice::Version: ${{ steps.version.outputs.latest_version }} (current)"
      - name: Check number of changed files
        run: |
          if [[ "${{ steps.path.outputs.file_path }}" == *".typ"* ]]; then
            echo "::error::More than one Typst source have been modified. Aborting."
            exit 1
          fi
