name: Register document version

on:
  workflow_call:
    inputs:
      file_name:
        required: true
        type: string
      file_version:
        required: true
        type: string

jobs:
  register:
    name: Update document version
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
      - name: Insert new version
        run: |
          sed -i "s/\"${{ inputs.file_name }}\": \".*\"/\"${{ inputs.file_name }}\": \"${{ inputs.file_version }}\"/" "documents.json"
      - name: Update register
        run: |
          git add documents.json
          git commit -am "Aggiornata versione ${{ inputs.file_name }}"
          git push origin src
