name: Typst on log update

on:
  pull_request:
    types: closed
    paths:
      - '**.csv'

concurrency:
  group: typst-${{ github.ref }}
  cancel-in-progress: true

jobs:
  fetch:
    if: github.event.pull_request.merged == true
    uses: Error-418-SWE/Documenti/.github/workflows/fetch_log_info.yml@src

  compile:
    if: github.event.pull_request.merged == true
    needs: fetch
    uses: Error-418-SWE/Documenti/.github/workflows/compile_document.yml@src
    with:
      file_name: ${{ needs.fetch.outputs.file_name }}
      file_path: ${{ needs.fetch.outputs.file_path }}

  deploy:
    if: github.event.pull_request.merged == true
    needs: fetch
    uses: Error-418-SWE/Documenti/.github/workflows/deploy_website.yml@src
    with:
      file_name: ${{ needs.fetch.outputs.file_name }}
      file_path: ${{ needs.fetch.outputs.file_path }}

  publish:
    if: github.event.pull_request.merged == true
    needs: [fetch, compile]
    runs-on: ubuntu-latest
    env:
      TARGET_BRANCH: 'main'

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
      - name: Update path
        id: publish_path
        run: echo "PUBLISH_PATH=$(dirname "${{ needs.fetch.outputs.file_path }}")" >> $GITHUB_OUTPUT
      - name: Output
        run: |
          echo "::notice::Source path: ${{ needs.fetch.outputs.file_path }}"
          echo "::notice::Compiled document path: ${{ steps.publish_path.outputs.PUBLISH_PATH }}"
      - name: Remove older version
        run: |
          git checkout $TARGET_BRANCH
          git rm --ignore-unmatch "${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.fetch.outputs.file_name }}*.pdf"
      - name: Grab document
        uses: actions/download-artifact@v3
        with:
          name: '${{ needs.fetch.outputs.file_name }}.pdf'
          path: '${{ github.workspace }}/${{ steps.publish_path.outputs.PUBLISH_PATH }}'
      - name: Rename file
        run: mv -v "${{ github.workspace }}/${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.fetch.outputs.file_name }}.pdf" "${{ github.workspace }}/${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.fetch.outputs.file_name }}_v${{ needs.fetch.outputs.current_version }}.pdf"
      - name: Publish document
        run: |
          git add "${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.fetch.outputs.file_name }}*.pdf"
          git commit -am "Publish document ${{ needs.fetch.outputs.file_name }} (v${{ needs.fetch.outputs.current_version }})"
          git push origin $TARGET_BRANCH
