name: Typst document workflow

on:
  #triggered when PR is (re)opened or synchronized (new commit to head)
  pull_request:
    types: [opened, reopened, synchronize, closed]
    paths:
      - '**.typ'
      - '!**template.typ'

jobs:
  common:
    runs-on: ubuntu-latest
    outputs:
      FILE_PATH: '${{ steps.path.outputs.FILE_PATH }}'
      FILE_NAME: '${{ steps.name.outputs.FILE_NAME }}'
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Get changed file
        id: files
        uses: tj-actions/changed-files@v40
        with:
          files: |
             **.typ
      - name: Extract path
        id: path
        run: |
          FILES="${{ steps.files.outputs.all_changed_files }}"
          echo "FILE_PATH=$(dirname "$FILES")" >> $GITHUB_OUTPUT
      - name: Extract name w/o extension
        id: name
        run: |
          FILES="${{ steps.files.outputs.all_changed_files }}"
          echo "FILE_NAME=$(basename "${FILES}" .typ)" >> $GITHUB_OUTPUT
      - name: Output to summary
        run: |
          echo "::notice::Modified files: ${{ steps.files.outputs.all_changed_files }}"
          echo "::notice::Path: ${{ steps.path.outputs.FILE_PATH }}"
          echo "::notice::File: ${{ steps.name.outputs.FILE_NAME }}"
      - name: Check number of changed files
        run: |
          if [[ "${{ steps.path.outputs.FILE_PATH }}" == *".typ"* ]]; then
            echo "::error::More than one Typst source have been modified. Aborting."
            exit 1
          fi

  log:
    needs: common
    uses: ggardin/Documenti/.github/workflows/changelogger.yml@src
    with:
      path: '${{ needs.common.outputs.FILE_PATH }}'

  compile:
    needs: [common, log]
    uses: ggardin/Documenti/.github/workflows/compiler.yml@src
    with:
      name: '${{ needs.common.outputs.FILE_NAME }}'
      path: '${{ needs.common.outputs.FILE_PATH }}'

  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: [common, compile]
    env:
      TARGET_BRANCH: 'main'

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Configure Git
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git fetch
      - name: Update path
        id: publish_path
        run: |
          echo "PUBLISH_PATH=$(dirname "${{ needs.common.outputs.FILE_PATH }}")" >> $GITHUB_OUTPUT
      - name: Output
        run: |
          echo "::notice::Old path: ${{ needs.common.outputs.FILE_PATH }}"
          echo "::notice::New path: ${{ steps.publish_path.outputs.PUBLISH_PATH }}"
      - name: Remove older version
        run: |
          git checkout $TARGET_BRANCH
          rm -f "${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.common.outputs.FILE_NAME }}.pdf"
          git rm --ignore-unmatch "${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.common.outputs.FILE_NAME }}.pdf"
      - name: Grab document
        uses: actions/download-artifact@v3
        with:
          name: '${{ needs.common.outputs.FILE_NAME }}.pdf'
          path: '${{ github.workspace }}/${{ steps.publish_path.outputs.PUBLISH_PATH }}'
      - name: Publish document
        run: |
          git add "${{ steps.publish_path.outputs.PUBLISH_PATH }}/${{ needs.common.outputs.FILE_NAME }}.pdf"
          git commit -am "Publish document ${{ needs.common.outputs.FILE_NAME }}.pdf"
          git push origin $TARGET_BRANCH
