name: Version handler

on:
  workflow_call:
    inputs:
      file_path:
        type: string
        required: true
      file_name:
        type: string
        required: true
    outputs:
      version:
        description: "The next and updated version of the document"
        value: ${{ jobs.update.outputs.version }}
      current_version:
        description: "The current version of the document"
        value: ${{ jobs.update.outputs.version }}

jobs:
  update:
    name: Compute versions
    runs-on: ubuntu-latest
    outputs:
      current_version: '${{ steps.current.outputs.version }}'
      version: '${{ steps.version.outputs.version }}'

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Get current version
        id: current
        run: |
          echo "VERSION=$(head -n2 "${{ inputs.file_path }}/${{ inputs.file_name }}.csv" | tail -n1 | cut -d',' -f1)" >> $GITHUB_OUTPUT
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Compute next version
        id: version
        run: |
          cp .github/scripts/file_version_handler.py ./
          echo "VERSION=$(python file_version_handler.py "${{ inputs.file_path }}" "${{ inputs.file_name }}")" >> $GITHUB_OUTPUT
      - name: Print versions to summary
        run: |
          echo "::notice::Current version: ${{ steps.current.outputs.version }}"
          echo "::notice::Updated version: ${{ steps.version.outputs.version }}"
