name: Version handler

on:
  workflow_call:
    inputs:
      file_path:
        type: string
        required: true
      file_name:
        type: string
        required: true
      current_version:
        type: string
        required: false
    outputs:
      next_version:
        description: "The next and updated version of the document"
        value: ${{ jobs.evaluate.outputs.next_version }}

jobs:
  evaluate:
    name: Evaluate version
    runs-on: ubuntu-latest
    outputs:
      next_version: '${{ steps.version.outputs.next_version }}'

    steps:
      - name: Set up Git repository on source branch
        uses: actions/checkout@v4
        with:
          path: head
      - name: Set up Git repository on main branch
        uses: actions/checkout@v4
        with:
          ref: src
          path: src
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Compute next version
        id: version
        run: |
          cp src/.github/scripts/manage_document_version.py ./
          echo "NEXT_VERSION=$(python manage_document_version.py "${{ inputs.file_path }}" "${{ inputs.file_name }}" ${{ inputs.current_version }})" >> $GITHUB_OUTPUT
      - name: Print next version to summary
        run: |
          echo "::notice::Next version: ${{ steps.version.outputs.next_version }}"
