name: Version handler

on:
  workflow_call:
    inputs:
      path:
        type: string
        required: true
      name:
        type: string
        required: true
    outputs:
      version:
        description: "The new and updated version of the document"
        value: ${{ jobs.fetch.outputs.updated_version }}

jobs:
  fetch:
    name: Fetch changed file info
    runs-on: ubuntu-latest
    outputs:
      updated_version: '${{ steps.version.outputs.VERSION }}'

    steps:
      - name: Output version
        id: version
        run: |
          echo "VERSION=v0" >> $GITHUB_OUTPUT

      - name: Set up Git repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Run Python script
        run: |
          cp .github/script.py ./
          version=$(python script.py  "${{ needs.common.outputs.FILE_PATH }}" "${{ needs.common.outputs.FILE_NAME }}")
          echo "$version" >> $GITHUB_OUTPUT
          echo "::notice::Updated version: $version"
